### PR TITLE
Add extensions to Schema

### LINKED ISSUE #43: Extensions in `Schema`
According to the OpenAPI specification, the `Schema` object should support extensions - https://swagger.io/specification/#schema-object

> This object MAY be extended with Specification Extensions.

### PR DESCRIPTION
**Pull request by JamesHinshelwood**
Fixes #43

### CODE REVIEW

**Comment by ahl** [comment]
Thanks for doing this; can you please fix the style check?

**Comment by james-bigpay** [comment]
@ahl Oops, sorry about that! Should be fixed now.

**Comment by JamesHinshelwood** [comment]
@ahl Oops sorry about that, should be fixed now

**Comment by ahl** [comment]
Looks great; thank you!

**Pull request merged**
