### PR TITLE
Breaking: Fix 'security' semantics between global and operation

### PR DESCRIPTION
**Pull request by swarkentin**
* Change `security` properties on both top level `OpenAPI` struct, as
  well as `Operation` to be wrapped in `Option`.
* Without this change, it is impossible to tell in the deserialized
  objects whether or not `security` has been omitted or explicitly set
  to an empty array - since either value deserializes to an empty `Vec`.
* Although this is a breaking change, it is vital to correctly handle the
  OpenAPI semantics of  `Operation.security`:
  >To remove a top-level security declaration, an empty array can be used

### CODE REVIEW

**Comment by ahl** [comment]
Thank you for submitting the PR; my apologies for the delayed response.

I see for operations that the absence of a `security` field has a meaning distinct from the presence of an empty array as you noted:

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#user-content-operationsecurity
> To remove a top-level security declaration, an empty array can be used.

What is the distinction between an empty array and omitting the `security` field in the `OpenAPI` object? Or did you elect to include the change for the `OpenAPI` struct for consistency?

Would you be amenable to adding a test? I'm not sure it's critical, but it could be useful in terms of demonstrating the functionality.

**Comment by swarkentin** [comment]
Thank you for taking a look. I appreciate the time you have taken to maintain this library!

> What is the distinction between an empty array and omitting the security field in the OpenAPI object?

Omitting the security field on a path means that global security should be used, if defined, or none at all.

An empty array overrides global security if it is defined. 

If a missing security field and an empty array were to both deserialize to an empty array, then it is impossible to tell the difference between the two cases noted above.

> Would you be amenable to adding a test?

Of course! Added!

**Comment by ahl** [comment]
> > What is the distinction between an empty array and omitting the security field in the OpenAPI object?
> 
> Omitting the security field on a path means that global security should be used, if defined, or none at all.

I was asking about omitting the `security` field on the `OpenAPI` object not the `Operation` object (where I agree with the distinction you've described).

**Comment by swarkentin** [comment]
> I was asking about omitting the security field on the OpenAPI object not the Operation

Thank you for clarifying. This a good question. I can't really think of any OpenAPI specification semantics that are lost between defining global/`OpenAPI.security` as an `Option` rather than an empty `Vec`. The only benefit I can think of is that `Option` better aligns with the actual specification as it can represent the lack of a `OpenAPI security` definition; leaving the interpretation up to users of the library rather than the library itself.

**Pull request merged**
